// Auto-generated by scripts/build_pwa_offline.py — precaches the whole dossier app.
const CACHE = 'boyne-v3';
const ASSETS = [
  "./",
  "./README-OPEN-ME.txt",
  "./audio/dossiers/boyne-valley_bv-beyond.mp3",
  "./audio/dossiers/boyne-valley_bv-causeway.mp3",
  "./audio/dossiers/boyne-valley_bv-cluster.mp3",
  "./audio/dossiers/boyne-valley_bv-daytrip.mp3",
  "./audio/dossiers/boyne-valley_bv-dowth.mp3",
  "./audio/dossiers/boyne-valley_bv-drombeg.mp3",
  "./audio/dossiers/boyne-valley_bv-dunaonghasa.mp3",
  "./audio/dossiers/boyne-valley_bv-giza.mp3",
  "./audio/dossiers/boyne-valley_bv-hook.mp3",
  "./audio/dossiers/boyne-valley_bv-knocknarea.mp3",
  "./audio/dossiers/boyne-valley_bv-knowth.mp3",
  "./audio/dossiers/boyne-valley_bv-knowth_lunar-calendar.mp3",
  "./audio/dossiers/boyne-valley_bv-knowth_moon-map.mp3",
  "./audio/dossiers/boyne-valley_bv-loughcrew.mp3",
  "./audio/dossiers/boyne-valley_bv-mythology.mp3",
  "./audio/dossiers/boyne-valley_bv-newgrange.mp3",
  "./audio/dossiers/boyne-valley_bv-newgrange_acoustics.mp3",
  "./audio/dossiers/boyne-valley_bv-newgrange_engineering.mp3",
  "./audio/dossiers/boyne-valley_bv-newgrange_suppression.mp3",
  "./audio/dossiers/boyne-valley_bv-poulnabrone.mp3",
  "./audio/dossiers/boyne-valley_bv-slane.mp3",
  "./audio/dossiers/boyne-valley_bv-tara.mp3",
  "./audio/dossiers/boyne-valley_bv-tara_geophysics.mp3",
  "./audio/dossiers/boyne-valley_bv-tara_hostages.mp3",
  "./audio/dossiers/boyne-valley_bv-uap.mp3",
  "./audio/dossiers/boyne-valley_bv-visit.mp3",
  "./audio/dossiers/kerry-coast_kerry-hook.mp3",
  "./audio/dossiers/manifest.json",
  "./audio/dossiers/northern-ireland_bv-causeway.mp3",
  "./audio/dossiers/northern-ireland_ni-hook.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-1975wave.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-corroboration.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-global.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-hook.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-howto.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-investigator.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-malmstrom.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-signature.mp3",
  "./audio/dossiers/nuclear-sentinel_ch-skeptic.mp3",
  "./audio/dossiers/occupant-reports_oc-cases.mp3",
  "./audio/dossiers/occupant-reports_oc-discipline.mp3",
  "./audio/dossiers/occupant-reports_oc-hook.mp3",
  "./audio/dossiers/occupant-reports_oc-invest.mp3",
  "./audio/dossiers/occupant-reports_oc-ruleout.mp3",
  "./audio/dossiers/physical-trace_tr-hook.mp3",
  "./audio/dossiers/physical-trace_tr-invest.mp3",
  "./audio/dossiers/physical-trace_tr-ladder.mp3",
  "./audio/dossiers/physical-trace_tr-ruleout.mp3",
  "./audio/dossiers/radar-visual_rv-chile.mp3",
  "./audio/dossiers/radar-visual_rv-hook.mp3",
  "./audio/dossiers/radar-visual_rv-invest.mp3",
  "./audio/dossiers/radar-visual_rv-jal.mp3",
  "./audio/dossiers/radar-visual_rv-ruleout.mp3",
  "./audio/dossiers/radar-visual_rv-why.mp3",
  "./audio/dossiers/recurring-hotspot_hs-hessdalen.mp3",
  "./audio/dossiers/recurring-hotspot_hs-hook.mp3",
  "./audio/dossiers/recurring-hotspot_hs-invest.mp3",
  "./audio/dossiers/recurring-hotspot_hs-others.mp3",
  "./audio/dossiers/recurring-hotspot_hs-ruleout.mp3",
  "./audio/dossiers/silent-triangle_st-belgium.mp3",
  "./audio/dossiers/silent-triangle_st-hook.mp3",
  "./audio/dossiers/silent-triangle_st-invest.mp3",
  "./audio/dossiers/silent-triangle_st-phoenix.mp3",
  "./audio/dossiers/silent-triangle_st-ruleout.mp3",
  "./audio/dossiers/silent-triangle_st-shape.mp3",
  "./audio/dossiers/sligo-northwest_bv-beyond.mp3",
  "./audio/dossiers/sligo-northwest_bv-knocknarea.mp3",
  "./audio/dossiers/sligo-northwest_sligo-hook.mp3",
  "./audio/dossiers/the-west_bv-dunaonghasa.mp3",
  "./audio/dossiers/the-west_bv-poulnabrone.mp3",
  "./audio/dossiers/the-west_west-hook.mp3",
  "./audio/dossiers/transmedium_tm-cases.mp3",
  "./audio/dossiers/transmedium_tm-hook.mp3",
  "./audio/dossiers/transmedium_tm-invest.mp3",
  "./audio/dossiers/transmedium_tm-ruleout.mp3",
  "./audio/dossiers/transmedium_tm-why.mp3",
  "./audio/dossiers/west-cork_bv-drombeg.mp3",
  "./audio/dossiers/west-cork_cork-hook.mp3",
  "./common.css",
  "./config.js",
  "./geographic-explorer-data.js",
  "./geographic-explorer-narratives.js",
  "./geographic-explorer.html",
  "./index.html",
  "./manifest.json",
  "./uap-case-store.js",
  "./uap-command-center.html",
  "./uap-command-data.js",
  "./uap-convergence.js",
  "./uap-dossiers.js",
  "./uap-geo.js",
  "./uap-investigator.js",
  "./uap-leyline-convergence.js",
  "./uts-integrity.js",
  "./vendor/MarkerCluster.Default.css",
  "./vendor/MarkerCluster.css",
  "./vendor/d3.v7.min.js",
  "./vendor/images/marker-icon.png",
  "./vendor/images/marker-shadow.png",
  "./vendor/leaflet.css",
  "./vendor/leaflet.js",
  "./vendor/leaflet.markercluster.js"
];
self.addEventListener('install', e => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(c => {
    // add individually so one 404 doesn't fail the whole install
    return Promise.all(ASSETS.map(u => c.add(u).catch(err => console.warn('skip', u, err))));
  }));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then(hit => hit || fetch(e.request).then(resp => {
      // runtime-cache same-origin GETs (covers anything missed at install)
      try { if (resp && resp.status === 200 && new URL(e.request.url).origin === self.location.origin) {
        const copy = resp.clone(); caches.open(CACHE).then(c => c.put(e.request, copy));
      } } catch (err) {}
      return resp;
    }).catch(() => caches.match('./uap-command-center.html')))
  );
});
